!classDefinition: #Neville category: 'Ej 1'!
DenotativeObject subclass: #Neville
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ej 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Neville class' category: 'Ej 1'!
Neville class
	instanceVariableNames: ''!

!Neville class methodsFor: 'as yet unclassified' stamp: 'N 3/21/2025 19:15:05'!
hola
	^'queeeeeeeeeeeeeeeeee'! !
